### PR TITLE
ObjOrPar as new default

### PR DESCRIPTION
**Pull request by mitwood**
Moving the object oriented parallel branch to the default version. Needs review of docs and example inputs to ensure they are updated to this version.

### CODE REVIEW

**Comment by athomps** [comment]
I am able to run master on my laptop, but not ObjOrPar. I think it is not detecting that I am running without mpi4py:
[athomps@s1025737 FitSNAP]$ python -m fitsnap3 --overwrite examples/Ta_Linear_JCP2014/Ta-example.in

    ______ _  __  _____  _   __ ___     ____  
   / ____/(_)/ /_/ ___/ / | / //   |   / __ \ 
  / /_   / // __/\__ \ /  |/ // /| |  / /_/ /
 / __/  / // /_ ___/ // /|  // ___ | / ____/ 
/_/    /_/ \__//____//_/ |_//_/  |_|/_/      

-----------
Reading input...
Finished reading input
No mpi4py detected, using fitsnap stubs...
numpy version:  1.17.2
scipy version:  1.4.1
pandas version:  1.0.3
-----------
Displaced_A15 : Detected  9  fitting on  9  testing on  0
Displaced_BCC : Detected  9  fitting on  9  testing on  0
Displaced_FCC : Detected  9  fitting on  9  testing on  0
Elastic_BCC : Detected  100  fitting on  100  testing on  0
Elastic_FCC : Detected  100  fitting on  100  testing on  0
GSF_110 : Detected  22  fitting on  22  testing on  0
GSF_112 : Detected  22  fitting on  22  testing on  0
Liquid : Detected  3  fitting on  3  testing on  0
Surface : Detected  7  fitting on  7  testing on  0
Volume_A15 : Detected  30  fitting on  30  testing on  0
Volume_BCC : Detected  21  fitting on  21  testing on  0
Volume_FCC : Detected  31  fitting on  31  testing on  0
'scrape_configs' took 249.84 ms on rank 0
'a' takes up  0.021960726007819176 % of the total memory 17.179869184 GB of RAM
ERROR:fitsnap3.io.outputs.outputs:'NoneType' object has no attribute 'bcast'
Traceback (most recent call last):
  File "/Users/athomps/netapp/codes/FitSNAP/FitSNAP_GitHub/FitSNAP/fitsnap3/__main__.py", line 43, in main
    snap.process_configs()
  File "/Users/athomps/netapp/codes/FitSNAP/FitSNAP_GitHub/FitSNAP/fitsnap3/parallel_tools.py", line 205, in timed
    result = method(*args, **kw)
  File "/Users/athomps/netapp/codes/FitSNAP/FitSNAP_GitHub/FitSNAP/fitsnap3/fitsnap.py", line 59, in process_configs
    self.calculator.create_a()
  File "/Users/athomps/netapp/codes/FitSNAP/FitSNAP_GitHub/FitSNAP/fitsnap3/calculators/lammps_snap.py", line 20, in create_a
    super().create_a()
  File "/Users/athomps/netapp/codes/FitSNAP/FitSNAP_GitHub/FitSNAP/fitsnap3/calculators/calculator.py", line 58, in create_a
    pt.slice_array('a', num_types=num_types)
  File "/Users/athomps/netapp/codes/FitSNAP/FitSNAP_GitHub/FitSNAP/fitsnap3/parallel_tools.py", line 352, in slice_array
    self.slice_a()
  File "/Users/athomps/netapp/codes/FitSNAP/FitSNAP_GitHub/FitSNAP/fitsnap3/parallel_tools.py", line 419, in slice_a
    self._comm_fitsnap("a_indices")
  File "/Users/athomps/netapp/codes/FitSNAP/FitSNAP_GitHub/FitSNAP/fitsnap3/parallel_tools.py", line 277, in _comm_fitsnap
    self.fitsnap_dict[name] = self._sub_comm.bcast(self.fitsnap_dict[name])
AttributeError: 'NoneType' object has no attribute 'bcast'
'main' took 5318.07 ms on rank 0

**Comment by cusentino** [comment]
I was able to successfully run this version of fitsnap on all the examples.  I have also switched over to this version in all of my current fits and everything is running smoothly.  

The only issue that I have run into is when I have two different versions of fitsnap in my python path.  Essentially I had an older version called "fitsnap3" that was using with my current fits.  I wanted to test this new version out without disrupting those runs so I added it as "newfitsnap" to my python path.  But when I try to run this with python, it looks like it initially tries to use the new version but then switches over to the older version.  So there is a conflict between the two versions.  It runs fine if I copy the fitsnap3 directory to where I am locally running the example I want to test.  I can provide some more details if needed.

**Comment by athomps** [comment]
@charlessievers what about adding an example that tests the xyz scraper?

**Comment by charlessievers** [comment]
> So there is a conflict between the two versions. It runs fine if I copy the fitsnap3 directory to where I am locally running the example I want to test. I can provide some more details if needed.

Do you use Conda environments? If so, we can fix this problem simply. Otherwise, you will have to keep removing and adding to python path by hand.

**Comment by athomps** [comment]
I think the underlying issue is not about the problem (two competing versions of fitsnap3 on the PYTHONPATH), but that it is very hard for the user to know what is going wrong.  It starts up the correct fitsnap, but then gets stuck later.  What is needed is a clear error message "Invalid FitSNAP version detected" or something similar.

**Comment by cusentino** [comment]
Yes, I agree with Aidan's point since it is not entirely clear what exactly is going on based on the output.  It seems like if you  have "fitsnap3" in you path it defaults to that even if you call a different version of fitsnap like the one I had named "newfitsnap" in my case.

I do use conda but I don't have a separate environment for when I run fitsnap.

**Comment by charlessievers** [comment]
I see your point. Would you share your output with the error and I'll add that into the newest PR.

Also, the newest PR has STUBS fixed.

**Comment by cusentino** [comment]
Yes, I should be able to generate that output and send it to you

**Review by cusentino — APPROVED** [review]
Recently checked this branch and it works for me.  One comment is that at some point I think we want to make sure we have clear instructions for setting up the parallel stuff since it's not straightforward

**Pull request merged**
