### PR TITLE
Write potential files and more

### PR DESCRIPTION
**Pull request by rohskopf**
This PR will include:

-  https://github.com/FitSNAP/FitSNAP/issues/168 
- https://github.com/FitSNAP/FitSNAP/issues/169
- Examples for loading potential into Python scripts for post fit error analysis on new data

### CODE REVIEW

**Comment by rohskopf** [comment]
Let's put all LAMMPS/potential files into a tarball (thanks @ldwillia :D)

**Comment by rohskopf** [comment]
Here's a description of new features that will make it easier to share fits properly.

First the `config` object makes a hash for each fit that gets echoed to the screen:
```
    ______ _  __  _____  _   __ ___     ____  
   / ____/(_)/ /_/ ___/ / | / //   |   / __ \ 
  / /_   / // __/\__ \ /  |/ // /| |  / /_/ /
 / __/  / // /_ ___/ // /|  // ___ | / ____/ 
/_/    /_/ \__//____//_/ |_//_/  |_|/_/      

-----23Sep22------
Reading input...
Hash: 7b3f95d401dd25c764ca0746da72de0f
Finished reading input
------------------
```
This hash gets used later when writing outputs so that we can better identify fits and hyperparams/settings associated with the fits. For example the coeff file has a hash:
```
# FitSNAP fit generated on 2023-02-03 08:31:24.604391
# Hash: 7b3f95d401dd25c764ca0746da72de0f

1 31
Ta 0.5 1.0
 -2.97994848705211979           #  B[0]
 ...
```
Likewise for the param file (which has extra info about the pair style and settings used):
```
# required
rcutfac 4.67637
twojmax 6

# optional
rcutfac 0.99363
rmin0 0.0
bzeroflag 0
wselfallflag 0
chemflag 0
bnormflag 0

# This file was generated by FitSNAP.
# Hash: 7b3f95d401dd25c764ca0746da72de0f
# FitSNAP REFERENCE section settings:
# units metal
# atom_style atomic
# pair_style hybrid/overlay zero 5.0 zbl 4.0 4.8
# pair_coeff * * zero
# pair_coeff * * zbl 73 73
```
These are packaged into a `.mod` file, which also has the hash:
```
# This file was generated by FitSNAP.
# Hash: 7b3f95d401dd25c764ca0746da72de0f

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta
```

We also make a `in.lammps` file which is a minimal usable LAMMPS script that loads the `.mod` file.

Finally, these are all packaged into a `fit-<hash>.tar` file that contains:

- *.snapcoeff
- *.snapparam
- *.mod
- in.lammps

In this example, these will be saved in `fit-7b3f95d401dd25c764ca0746da72de0f.tar`.

Going forward, we can expect people to send this tarball when sharing fits. This will be explained in the docs.

**Comment by athomps** [comment]
This is a big improvement.  This might be a time to implement/reactivate echoing of all input to the screen and/or a log file..

**Comment by rohskopf** [comment]
We also write `*.mod` files that echo the reference potential, satisfying #168 for ACE.

**Review by mitwood — APPROVED** [review]
*chefs kiss* This will really help the usability and reproducibility of potentials generated. Thanks for this.

**Pull request merged**
