### PR TITLE
Functional code, ParallelTools small updates, and docs

### PR DESCRIPTION
**Pull request by rohskopf**
Here we update error analysis to be more functional by allowing optional inputs (A matrix, b and w arrays). 

This allows more flexible use in library mode. We can supply previously calculated descriptors into the error analysis function.

### CODE REVIEW

**Comment by rohskopf** [comment]
To do a fit with existing data we need 4 things:

1. The `a` matrix
2. The `b` array of truths
3. The `w` array of weights
4. A dictionary containing a `Testing` key with bools determining which `a` matrix rows to train to.

So fitting and error analysis with these optional inputs looks like this:

```
fs.solver.perform_fit(a=amat, b=b, w=w, fs_dict=fs_dict)
fs.solver.error_analysis(a=amat, b=b, w=w, fs_dict=fs_dict)
```
If these arguments are not supplied, then fitsnap will use the data in `fs.pt.shared_arrays`.

**Comment by rohskopf** [comment]
For parallel library use such as many fits on many cores, we need an optional arg to `perform_fit` and `error_analysis` for which rank to run on.

**Comment by rohskopf** [comment]
> For parallel library use such as many fits on many cores, we need an optional arg to perform_fit and error_analysis for which rank to run on.

This is satisfied. By fitting on `pt._rank == 0`, we are fitting on the first process in the communicator. If the communicator is split, this will still be a different process 👍

**Review by megmcca — APPROVED** [review]
Adds very useful new functionality to allow fitting from files and a lot of new documentation, looks great!

**Pull request merged**
