### PR TITLE
added chemsnap capabilities and changed charges option a bit

### PR DESCRIPTION
**Pull request by charlessievers**
I ran all of the current examples and compared snapcoeff files.

### CODE REVIEW

**Comment by mitwood** [comment]
New input variables need definition in docs/TEMPLATE.in.
i.e.
[MODEL]
alloyflag =        # ()
wselfallflag =     # ()
bnormflag =        # ()
[REFERENCE]
charges =                   # ()
kspace_style =              # ()

See other lines in docs/TEMPLATE.in to write your description. 

Will need a directory added in examples/ to demonstrate these changes, can wait on publication ( @cusentino , @athomps ).

**Comment by mitwood** [comment]
Your eshift changes in scrape don't seem to be element specific. Are you adding a per-atom energy? If so document it as such (docs/TEMPLATE.in). @charlessievers

**Comment by charlessievers** [comment]
> Your eshift changes in scrape don't seem to be element specific. Are you adding a per-atom energy? If so document it as such (docs/TEMPLATE.in). @charlessievers

I am adding per atom energy and they are based off the element type. (See scrape.py 214-216)

**Comment by mitwood** [comment]
@athomps @charlessievers Double check that you want to use the input variable names alloyflag, wselfallflag and bnormflag. These do not have to match the LAMMPS variables and ca be chosen such that they are more intuitive to users. Is bnormflag only usable with alloyflag=1? Are there other couplings between variables that need to be documented?

Code looks good though.

**Comment by charlessievers** [comment]
@mitwood great idea we should make them more user friendly. @athomps do you have any preferences for what you would like the user end flags to be called? bnormflag is usable for all cases. I think whatever we name bnormflag should remain the same as the pair compute flag since they must be used together. Ideally, we would have just always had bnormflag set to on.

**Comment by mitwood** [comment]
@charlessievers @athomps 
I don't think we need to expose bnormflag to FitSNAP users, rather if alloyflag=1 then we silently turn on bnormflag=1 in the background, else it defaults to 0. 

Also, I don't like that kspace_style is now being treated as a mandatory reference potential. We should generalize this into 'any additional lammps commands' that can be specified after pair_style. With this change we do not need charges to be defined in the FitSNAP input file, there was already the capability to do this if charges were present in the training data. If users want to use a column reference potential then their per-atom charges need to be added in the training files.

**Comment by charlessievers** [comment]
> @charlessievers @athomps
> I don't think we need to expose bnormflag to FitSNAP users, rather if alloyflag=1 then we silently turn on bnormflag=1 in the background, else it defaults to 0.

I believe it will speed up the potential though. It does already default to zero.

> Also, I don't like that kspace_style is now being treated as a mandatory reference potential. We should generalize this into 'any additional lammps commands' that can be specified after pair_style. 

What do you mean by mandatory reference potential, do you just mean within the documentation?
Because it is not mandatory in the actual code. I pop it from the dict if the fallback occurs.

>With this change we do not need charges to be defined in the FitSNAP input file, there was already the capability to do this if charges were present in the training data. If users want to use a column reference potential then their per-atom charges need to be added in the training files.

I saw the charge capability earlier, however there are no charges in the chemsnap examples training data, so I allowed both to be used. (see lines 210-217 in runlammps.py)

**Comment by athomps** [comment]
@charlessievers I agree with @mitwood  about bnormflag. Since it does not change the physics, it should remain hidden in the LAMMPS code, turned on if alloyflag=1.

**Comment by athomps** [comment]
@charlessievers since the charge and kspace options are unrelated to ChemSNAP, these should be excluded from this PR.

**Comment by charlessievers** [comment]
> @charlessievers since the charge and kspace options are unrelated to ChemSNAP, these should be excluded from this PR.

@athomps @mitwood  I see now what you both are saying. I will remove them tomorrow. I will also hide bnormflag in FitSNAP. @athomps would you like me to do the same for LAMMPS?

**Comment by charlessievers** [comment]
> @charlessievers I agree with @mitwood about bnormflag. Since it does not change the physics, it should remain hidden in the LAMMPS code, turned on if alloyflag=1.

I will hide both FitSNAP and LAMMPS bnormflags.

**Pull request merged**
