### PR TITLE
Minor I/O fixes and improvements

### PR DESCRIPTION
**Pull request by megmcca**
This PR aims to fix/improve some input/output features of FitSNAP: 
- Error messages in the scrape and calculation steps have been updated to print a faulty configuration object's group and filename for easier debugging.
- Minor bugs with certain user-chosen input variables not being updated properly (for example, with Pytorch output_file names) have been squished.
- A FitSNAP instance's "config" object can differ quite a bit from original input "settings" object (file or Python dict) because FitSNAP adds and alters information based on the system settings, the type of fit, and so on. Two new functions have been added to `input.py` to let users see and use that information, "view_state" and "convert_to_dict."

### CODE REVIEW

**Comment by rohskopf** [comment]
Finite difference test for descriptor derivatives failed with segfault. Rerunning.

**Comment by athomps** [comment]
@rohskopf I'm glad you have this finite difference test!

**Comment by megmcca** [comment]
yeah i've been trying to hunt down the issue, thanks for picking up on this @rohskopf!

on my local Red Hat workstation running with 2 cores, running the test_fd_single_elem code w/o pytest, it looks something like MPI is not populating the rank == 1 core with configurations.
serial runs without issue.

weirdly, rolling back to previous commits that failed doesn't seem to solve the issue, at least on my local box...

**Comment by megmcca** [comment]
thanks @rohskopf for nailing down the Pytorch version bug!

i've updated the two affected files, and left that sub_rank decorator alone (well-tested MPI code should never be recklessly abandoned)

**Review by rohskopf — APPROVED** [review]

**Pull request merged**
