### PR TITLE
Obj or par

### PR DESCRIPTION
**Pull request by charlessievers**
Updated output slightly for input portion, added ability to modify group table sections, group table no longer needs to be in separate file, testing and training does not need to be on whole set and can be set individually.

### CODE REVIEW

**Comment by mitwood** [comment]
Charlie, I would like to see an update input file that reflects this merger of group list info. Also, what is going on in L66-69 of scrape.py? Is this shackling the training+testing sizes = 1? Or is it possible to use less than the full amount of data (i.e. 0.5 training, 0.25 testing)?

**Comment by charlessievers** [comment]
> Charlie, I would like to see an updated input file that reflects this merger of group list info. 

Will do.

> Also, what is going on in L66-69 of scrape.py? Is this shackling the training+testing sizes = 1? Or is it possible to use less than the full amount of data (i.e. 0.5 training, 0.25 testing)?

This is keeping backwards compatibility with using size as a group table section and training. I think the confusion is coming from the fact that I accidentally swapped the words training and testing, will fix that. In the end, I am just adding the capability to put how many files you would like to train and test on. I made the new capability not percentage based but based on the number of files.

**Comment by mitwood** [comment]
> This is keeping backwards compatibility with using size as a group table section and training. ... In the end, I am just adding the capability to put how many files you would like to train and test on. I made the new capability not percentage based but based on the number of files.

I would be in favor of dropping the 'declare number of files' function in favor or only fractional amounts from here on out. Odds are that people are going to use our scrapers as a black box as well and won't know how many training configs they are pulling in anyway.

**Comment by charlessievers** [comment]
> I would be in favor of dropping the 'declare number of files' function in favor or only fractional amounts from here on out. Odds are that people are going to use our scrapers as a black box as well and won't know how many training configs they are pulling in anyway.

I see, I was going the opposite way because I like specifying everything explicitly. I see your point about the users tho, I will change it to be percentage based then.

**Pull request merged**
