### PR TITLE
Obj or par

### PR DESCRIPTION
**Pull request by charlessievers**
Complete Working version of FitSNAP. Getting errors efficiently threw me for a bit of a loop. There were too many ways to process them. We still need more multi node functionality. I think the error setup is rather elegant. Sorry this part took me so long, I just wanted to do it right.

### CODE REVIEW

**Comment by mitwood** [comment]
@athomps @cusentino Please provide a review of this code. It, as Charlie says, is a fully functioning version and would do well with some outside testing.

**Comment by charlessievers** [comment]
> Ncie work @charlessievers! One thing I don't see is any testing. It is important that all the existing examples run and give equivalent results w.r.t. the previous standards.

I tested each example before submitting this pull request.

**Comment by mitwood** [comment]
@charlessievers Can you take a picture of the code 'workflow' thing we sketched, maybe I can use some of this telecommuting time to put together a format graphic of that.

**Comment by charlessievers** [comment]
> @charlessievers Can you take a picture of the code 'workflow' thing we sketched and email it to me, maybe I can use some of this telecommuting time to put together a formal graphic of that.

Just sent it.

**Comment by charlessievers** [comment]
Question for all three of you. A few ideas I had for this week are: Commenting the code, adding multimode capabilities, making documentation, and updating the examples. Have any preferences as to what my priorities should be?

**Comment by athomps** [comment]
I think commenting should be kept to a minimum, as anything elaborate becomes outdated.  

documentation is essential.  The goal is to define all user input options and resultant behavior.

updating examples is also essential

**Comment by cusentino** [comment]
This looks good, nice work Charlie!  I agree with Aidan's comment on documentation and making sure the examples work.  I could test it on one of my current potential fits.

**Comment by charlessievers** [comment]
> This looks good, nice work Charlie! 
Thank you!
>I agree with Aidan's comment on documentation and making sure the examples work. 
I will focus on documentation this week.
>I could test it on one of my current potential fits.
That would be great. I am excited to hear how it goes.

**Pull request merged**
