### PR TITLE
fixed group error bug reporting errors for wrong respective group names

### PR DESCRIPTION
**Pull request by charlessievers**
I noticed that there was a bug in the linear fit error reporting. I updated the InP example.

@cusentino would you double check that everything checks out for the InP example and add a new screen.fitsnap3 to the InP examples standard folder?

### CODE REVIEW

**Comment by mitwood** [comment]
Code looks good. Will wait on @cusentino for group error confirmation with these changes.

**Comment by cusentino** [comment]
When I try to run the InP example, I get an error that "SCRAPER was not found in fitsnap sections".  Any idea why this might be?

**Comment by mitwood** [comment]
The following should be included in the example input file:
[SCRAPER]
scraper = JSON

If it isnt, please add and commit changes.

**Comment by charlessievers** [comment]
@cusentino That is odd, what machine are you using? 
@mitwood Does this happen for you as well? 
I see no problem running the example on my end, I even tested this on a cluster.

**Comment by cusentino** [comment]
I ran it on both my desktop and on the clusters.  I see the issue for both.  I did see that the [SCRAPER] section was missing  in the input file

**Comment by charlessievers** [comment]
I must have deleted it on accident, I see the same. I am not sure why yours fails without it. It should kick back up to default. Does the example work when you add back in that section of the config file?

**Comment by cusentino** [comment]
It still fails even when I put the scraper section back in

**Comment by mitwood** [comment]
Double check your versions of config parser?

**Comment by charlessievers** [comment]
Who knows, you may also want to double check everything is up to date on git?
@mitwood The example runs for you, correct?

**Comment by cusentino** [comment]
The issues I have been seeing are fixed now.  I get the same coefficients and group errors as before so everything looks good to me.  I also updated the screen output for the InP example

**Comment by charlessievers** [comment]
@cusentino Are you sure nothing has changed in the group errors section? They should be accurate now, but the ones in the 20Jun20_standard folder before this PR are wrong. 
Or do you mean that they are the same with respect to your group errors from master branch FitSNAP?

**Comment by cusentino** [comment]
I meant that they are the same with respect to the group errors reported in the paper

**Pull request merged**
