### PR TITLE
Nonlinear and Dataframes

### PR DESCRIPTION
**Pull request by charlessievers**
Distributed Lists
Data Frames
Nonlinear Fitting
Jax
Pytorch

### CODE REVIEW

**Comment by charlessievers** [comment]
@lubbersnick would you look over the non-linear parts as well if you get a chance.

**Comment by dmozapiain2001** [comment]
I tried to run this code and obtained the following error:

`python3 -m fit_snap_Charlie_PR Be-example.in

    ______ _  __  _____  _   __ ___     ____  
   / ____/(_)/ /_/ ___/ / | / //   |   / __ \ 
  / /_   / // __/\__ \ /  |/ // /| |  / /_/ /
 / __/  / // /_ ___/ // /|  // ___ | / ____/ 
/_/    /_/ \__//____//_/ |_//_/  |_|/_/      

-----7Feb22------
Reading input...
Finished reading input
------------------
mpi4py version:  3.1.3
numpy version:  1.22.3
scipy version:  1.8.0
pandas version:  1.4.1
LAMMPS (17 Feb 2022)
-----------
Total wall time: 0:00:00
Using LAMMPSSNAP as FitSNAP calculator
all_train : Detected  4090  fitting on  4090  testing on  0
'scrape_configs' took 4977.78 ms on rank 0
>>> Matrix of descriptors takes up  0.0004 % of the total memory: 270.4244 GB
ERROR:fit_snap_Charlie_PR.io.outputs.outputs:'list' object has no attribute 'get_list'
Traceback (most recent call last):
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/__main__.py", line 43, in main
    snap.process_configs()
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/parallel_tools.py", line 246, in timed
    result = method(*args, **kw)
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/fitsnap.py", line 65, in process_configs
    self.calculator.collect_distributed_lists()
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/calculators/calculator.py", line 75, in collect_distributed_lists
    pt.fitsnap_dict[key] = pt.fitsnap_dict[key].get_list()
AttributeError: 'list' object has no attribute 'get_list'
Traceback (most recent call last):
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/__main__.py", line 52, in <module>
    main()
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/parallel_tools.py", line 246, in timed
    result = method(*args, **kw)
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/__main__.py", line 48, in main
    output.exception(e)
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/io/outputs/outputs.py", line 50, in exception
    pt.exception(err)
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/parallel_tools.py", line 525, in exception
    raise err
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/__main__.py", line 43, in main
    snap.process_configs()
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/parallel_tools.py", line 246, in timed
    result = method(*args, **kw)
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/fitsnap.py", line 65, in process_configs
    self.calculator.collect_distributed_lists()
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/calculators/calculator.py", line 75, in collect_distributed_lists
    pt.fitsnap_dict[key] = pt.fitsnap_dict[key].get_list()
AttributeError: 'list' object has no attribute 'get_list'`

**Comment by charlessievers** [comment]
@dmozapiain2001 What is the Be example?

**Comment by dmozapiain2001** [comment]
it is a dataset I have of beryllium only configurations. I can send it to you if needed

**Comment by dmozapiain2001** [comment]
to be more specific, they are the configurations of the WBe_PRB2019 dataset that only have beryllium.

**Comment by dmozapiain2001** [comment]
Also I attempted to run this code on the WBe_PRB2019 dataset and got the following:

`python3 -m fit_snap_Charlie_PR WBe-example.in 

    ______ _  __  _____  _   __ ___     ____  
   / ____/(_)/ /_/ ___/ / | / //   |   / __ \ 
  / /_   / // __/\__ \ /  |/ // /| |  / /_/ /
 / __/  / // /_ ___/ // /|  // ___ | / ____/ 
/_/    /_/ \__//____//_/ |_//_/  |_|/_/      

-----7Feb22------
Reading input...
Finished reading input
------------------
mpi4py version:  3.1.3
numpy version:  1.22.3
scipy version:  1.8.0
pandas version:  1.4.1
LAMMPS (17 Feb 2022)
-----------
Total wall time: 0:00:00
Using LAMMPSSNAP as FitSNAP calculator
001FreeSurf : Detected  34  fitting on  34  testing on  0
010FreeSurf : Detected  36  fitting on  36  testing on  0
100FreeSurf : Detected  20  fitting on  20  testing on  0
Defect_BCrowd : Detected  22  fitting on  22  testing on  0
Defect_BOct : Detected  22  fitting on  22  testing on  0
Defect_BSplit : Detected  22  fitting on  22  testing on  0
Defect_BTetra : Detected  46  fitting on  46  testing on  0
Defect_Crowd : Detected  22  fitting on  22  testing on  0
Defect_Oct : Detected  22  fitting on  22  testing on  0
Defect_Tet : Detected  10  fitting on  10  testing on  0
Defect_Vacancy : Detected  13  fitting on  13  testing on  0
DFTMD_1000K : Detected  505  fitting on  505  testing on  0
DFTMD_300K : Detected  404  fitting on  404  testing on  0
Elast_BCC_Shear : Detected  978  fitting on  978  testing on  0
Elast_BCC_Vol : Detected  1000  fitting on  1000  testing on  0
Elast_FCC_Shear : Detected  371  fitting on  371  testing on  0
Elast_FCC_Vol : Detected  1000  fitting on  1000  testing on  0
Elast_HCP_Shear : Detected  244  fitting on  244  testing on  0
Elast_HCP_Vol : Detected  1001  fitting on  1001  testing on  0
EOS_BCC : Detected  101  fitting on  101  testing on  0
EOS_FCC : Detected  301  fitting on  301  testing on  0
EOS_HCP : Detected  100  fitting on  100  testing on  0
StackFaults : Detected  6  fitting on  6  testing on  0
Liquids : Detected  75  fitting on  75  testing on  0
DFT_MD_1000K : Detected  1562  fitting on  1562  testing on  0
DFT_MD_300K : Detected  1798  fitting on  1798  testing on  0
ElasticDeform_Shear : Detected  1483  fitting on  1483  testing on  0
ElasticDeform_Vol : Detected  2833  fitting on  2833  testing on  0
EOS : Detected  1113  fitting on  1113  testing on  0
WSurface_BeAdhesion : Detected  381  fitting on  381  testing on  0
BCC_ForceLib_W110 : Detected  5  fitting on  5  testing on  0
BCC_ForceLib_W111 : Detected  3  fitting on  3  testing on  0
BCC_ForceLib_WOct : Detected  4  fitting on  4  testing on  0
BCC_ForceLib_WTet : Detected  3  fitting on  3  testing on  0
dislocation_quadrupole : Detected  98  fitting on  98  testing on  0
Disordered_Struc : Detected  27  fitting on  27  testing on  0
Divacancy : Detected  39  fitting on  39  testing on  0
EOS_Data : Detected  125  fitting on  125  testing on  0
gamma_surface : Detected  6183  fitting on  6183  testing on  0
gamma_surface_vacancy : Detected  750  fitting on  750  testing on  0
md_bulk : Detected  60  fitting on  60  testing on  0
slice_sample : Detected  2000  fitting on  2000  testing on  0
surface : Detected  180  fitting on  180  testing on  0
vacancy : Detected  420  fitting on  420  testing on  0
'scrape_configs' took 5470.74 ms on rank 0
>>> Matrix of descriptors takes up  0.5769 % of the total memory: 270.4244 GB
WARNING: Configuration has no SNAP neighbors
WARNING: Configuration has no SNAP neighbors
WARNING: Configuration has no SNAP neighbors
WARNING: Configuration has no SNAP neighbors`

**Comment by dmozapiain2001** [comment]
after all those warning messages this is the final error:

WARNING: Configuration has no SNAP neighbors
WARNING: Configuration has no SNAP neighbors
WARNING: Configuration has no SNAP neighbors
ERROR:fit_snap_Charlie_PR.io.outputs.outputs:'list' object has no attribute 'get_list'
Traceback (most recent call last):
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/__main__.py", line 43, in main
    snap.process_configs()
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/parallel_tools.py", line 246, in timed
    result = method(*args, **kw)
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/fitsnap.py", line 65, in process_configs
    self.calculator.collect_distributed_lists()
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/calculators/calculator.py", line 75, in collect_distributed_lists
    pt.fitsnap_dict[key] = pt.fitsnap_dict[key].get_list()
AttributeError: 'list' object has no attribute 'get_list'
Traceback (most recent call last):
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/__main__.py", line 52, in <module>
    main()
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/parallel_tools.py", line 246, in timed
    result = method(*args, **kw)
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/__main__.py", line 48, in main
    output.exception(e)
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/io/outputs/outputs.py", line 50, in exception
    pt.exception(err)
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/parallel_tools.py", line 525, in exception
    raise err
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/__main__.py", line 43, in main
    snap.process_configs()
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/parallel_tools.py", line 246, in timed
    result = method(*args, **kw)
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/fitsnap.py", line 65, in process_configs
    self.calculator.collect_distributed_lists()
  File "/home/dmonte/anaconda3/envs/fit_snap/lib/python3.8/site-packages/fit_snap_Charlie_PR/calculators/calculator.py", line 75, in collect_distributed_lists
    pt.fitsnap_dict[key] = pt.fitsnap_dict[key].get_list()
AttributeError: 'list' object has no attribute 'get_list'

**Comment by charlessievers** [comment]
@dmozapiain2001 Fixed the issue and also sped up the calculation of group errors.

**Review by mitwood — APPROVED** [review]
The changes here represent a significant advance in capabilities, but are still in need of polish that we can follow up on in future PRs. 

-documentation of the NN fitting is a high priority as this will become a heavily used feature.
-detailed errors are now unavailable with the new dataframes
-group weights utilized in NN model fitting?

**Pull request merged**
