### PR TITLE
Multi-element ACE descriptors with symmetric ACE library interface

### PR DESCRIPTION
**Pull request by jmgoff**
Multi-element ACE descriptors may be calculated with the ML-PACE package in lammps with version:
lammps-user-pace-v.2021.10.25
FitSNAP uses this LAMMPS package and the symmetric ACE library to fit ACE energy models for atomic systems with 1+ element types.

The ACE library must be downloaded separately from FitSNAP.

Depricated PACE example fits with FitSNAP have been removed and replaced with a simple Tantalum example.

### CODE REVIEW

**Review by rohskopf — DISMISSED** [review]
Awesome. Can we get an updated procedure for downloading and installing the ACE library?

**Comment by rohskopf** [comment]
Looking good. Gonna move examples to a new repo and add nonlinear fitting.

**Review by rohskopf — APPROVED** [review]
Big updates to ACE fitting. We have linear and nonlinear ACE fitting working here.

**Comment by megmcca** [comment]
Getting the little crash noted above (issue #154) was actually a really cool surprise this morning ;-) 
Awesome that we now have linear/nonlinear ACE fitting up and running! Thanks

**Pull request merged**
