### PR TITLE
Mixed 2J and other QoL

### PR DESCRIPTION
**Pull request by mitwood**
Fits are now permitted where 2J_max is element-specific, this also brought along streamlined formatting of input files for multi-element fits. 
Detailed error reporting and direct output of descriptor and truth matrices available, see [EXTRAS] section of example input files. 
Input sections/keys are now checked against what is expected/necessary, warnings are printed to screen. 
Error reporting files have been drastically simplified.

### CODE REVIEW

**Review by athomps — APPROVED** [review]
These are nice improvements.  I was able to run the Ta_Linear example without much trouble, just needed to read error message and do `conda install tabulate`.  The new Ta_Linear reference output contains warnings that I did not see `Found unmatched variable in GROUPS section...`  Also, I think the warning that is still generated `Found unmatched variable in BISPECTRUM section of input:  alloyflag` should trigger a fatal error, so input file will need to be updated. Same for the other examples and the standards.

**Comment by athomps** [comment]
Let me know if you want me to test anything else. Also, I was happy to see that the mpi4py stubs module is working.

**Comment by cusentino** [comment]
I was also able to run both the Ta examples.  I also tested it out on one of the current WH fits and it also runs fine and reproduces the same coefficients

**Review by snikolov3 — COMMENTED** [review]
The Ta linear/quadratic examples run fine in serial/parallel after installing tabulate module. I do see the warning "Found unmatched variable in BISPECTRUM section of input:  alloyflag" which Aidan mentioned. The InP and WBe examples fail in parallel on attaway compute node. I attached error below:

-----20May21------
Reading input...
>>> Found unmatched variable in BISPECTRUM section of input:  alloyflag
Finished reading input
------------------
mpi4py version:  3.0.3
numpy version:  1.19.5
scipy version:  1.5.4
pandas version:  1.1.5
LAMMPS (22 Oct 2020)
-----------
001FreeSurf : Detected  34  fitting on  34  testing on  0
010FreeSurf : Detected  36  fitting on  36  testing on  0
100FreeSurf : Detected  20  fitting on  20  testing on  0
Defect_BCrowd : Detected  22  fitting on  22  testing on  0
Defect_BOct : Detected  22  fitting on  22  testing on  0
Defect_BSplit : Detected  22  fitting on  22  testing on  0
Defect_BTetra : Detected  46  fitting on  46  testing on  0
Defect_Crowd : Detected  22  fitting on  22  testing on  0
Defect_Oct : Detected  22  fitting on  22  testing on  0
Defect_Tet : Detected  10  fitting on  10  testing on  0
Defect_Vacancy : Detected  13  fitting on  13  testing on  0
DFTMD_1000K : Detected  505  fitting on  505  testing on  0
DFTMD_300K : Detected  404  fitting on  404  testing on  0
Elast_BCC_Shear : Detected  978  fitting on  978  testing on  0
Elast_BCC_Vol : Detected  1000  fitting on  1000  testing on  0
Elast_FCC_Shear : Detected  371  fitting on  371  testing on  0
Elast_FCC_Vol : Detected  1000  fitting on  1000  testing on  0
Elast_HCP_Shear : Detected  244  fitting on  244  testing on  0
Elast_HCP_Vol : Detected  1001  fitting on  1001  testing on  0
EOS_BCC : Detected  101  fitting on  101  testing on  0
EOS_FCC : Detected  301  fitting on  301  testing on  0
EOS_HCP : Detected  100  fitting on  100  testing on  0
StackFaults : Detected  6  fitting on  6  testing on  0
Liquids : Detected  75  fitting on  75  testing on  0
DFT_MD_1000K : Detected  1562  fitting on  1562  testing on  0
DFT_MD_300K : Detected  1798  fitting on  1798  testing on  0
ElasticDeform_Shear : Detected  1483  fitting on  1483  testing on  0
ElasticDeform_Vol : Detected  2833  fitting on  2833  testing on  0
EOS : Detected  1113  fitting on  1113  testing on  0
WSurface_BeAdhesion : Detected  381  fitting on  381  testing on  0
BCC_ForceLib_W110 : Detected  5  fitting on  5  testing on  0
BCC_ForceLib_W111 : Detected  3  fitting on  3  testing on  0
BCC_ForceLib_WOct : Detected  4  fitting on  4  testing on  0
BCC_ForceLib_WTet : Detected  3  fitting on  3  testing on  0
dislocation_quadrupole : Detected  98  fitting on  98  testing on  0
Disordered_Struc : Detected  27  fitting on  27  testing on  0
Divacancy : Detected  39  fitting on  39  testing on  0
EOS_Data : Detected  125  fitting on  125  testing on  0
gamma_surface : Detected  6183  fitting on  6183  testing on  0
gamma_surface_vacancy : Detected  750  fitting on  750  testing on  0
md_bulk : Detected  60  fitting on  60  testing on  0
slice_sample : Detected  2000  fitting on  2000  testing on  0
surface : Detected  180  fitting on  180  testing on  0
vacancy : Detected  420  fitting on  420  testing on  0
'scrape_configs' took 17601.49 ms on rank 0
>>> Matrix of descriptors takes up  0.7746 % of the total memory: 201.4210 GB
--------------------------------------------------------------------------
It appears as if there is not enough space for /tmp/ompi.swa1402.97788/pid.234266/1/0/shared_window_8.swa1402 (the shared-memory backing
file). It is likely that your MPI job will now either abort or experience
performance degradation.

  Local host:  swa1402
  Space Requested: 1560139656 B
  Space Available: 483221504 B
--------------------------------------------------------------------------
[swa1402:234272] *** Process received signal ***
[swa1402:234272] Signal: Segmentation fault (11)
[swa1402:234272] Signal code: Address not mapped (1)

**Review by athomps — APPROVED** [review]
Looks good.

**Comment by mitwood** [comment]
@snikolov3 Can you confirm this works with the SNAP+SPIN models?

**Comment by charlessievers** [comment]
Hey @snikolov3 where did that error about memory pop up? 
It may be an old issue that is solved by appending `--mca btl_vader_backing_directory /tmp` as an mpirun option
`mpirun --mca btl_vader_backing_directory /tmp -n $SLURM_NTASKS -m fitsnap3 Ta-example.in`
If you are already doing this, then I will try a build on attaway.

**Pull request merged**
