### PR TITLE
Updated fitsnap to work with updated chemsnap PR

### PR DESCRIPTION
**Pull request by charlessievers**

### CODE REVIEW

**Comment by mitwood** [comment]
This will sit until LAMMPS supports these syntax changes in its' distributed version.

**Comment by charlessievers** [comment]
> This will sit until LAMMPS supports these syntax changes in its' distributed version.

Good call.

**Comment by athomps** [comment]
Something is not quite right with this example, see attached plot.  One of the P coefficients is much larger than the rest. Moreover, this is not the case for the version in LAMMPS examples/snap.
[coeffs.pdf](https://github.com/FitSNAP/FitSNAP/files/4795916/coeffs.pdf)

**Comment by athomps** [comment]
@cusentino @charlessievers please take a look at previous comment

**Comment by athomps** [comment]
Diffs show the behavior more clearly. The bad actor is:

 -0.000023632674 # B[25, 5, 4, 5] Block = 1 Type = P
--
 -2.3882638305239636
[diffs.pdf](https://github.com/FitSNAP/FitSNAP/files/4795981/diffs.pdf)

**Comment by charlessievers** [comment]
> Diffs show the behavior more clearly. The bad actor is:
> 
> ```
>  -0.000023632674 # B[25, 5, 4, 5] Block = 1 Type = P
> --
>  -2.3882638305239636
> ```
> 
> [diffs.pdf](https://github.com/FitSNAP/FitSNAP/files/4795981/diffs.pdf)

-2.38826383035586898e-05       #  B[25, 5, 4, 5] 

Aidan is it possible that you are not accounting for scientific notation?

**Comment by athomps** [comment]
100%
[diffs.pdf](https://github.com/FitSNAP/FitSNAP/files/4796567/diffs.pdf)

**Comment by athomps** [comment]
The LAMMPS PR #1971 for ChemSNAP has been into master.

**Pull request merged**
