### PR TITLE
Adding fitsnap library active learning example

### PR DESCRIPTION
**Pull request by ldwillia**
This is functional but I am still building out the analysis, plotting, and settings control options. Feel free to pull it in now or leave it in PR mode until it is done being developed.

Also, this PR removes an unused 'ref' shared array.

### CODE REVIEW

**Comment by rohskopf** [comment]
Running the example as is, I get an error:

`FileNotFoundError: [Errno 2] No such file or directory: 'training_JSON/GSF_112'`

So I put an empty `GSF_112` directory (also did this for `Volume_BCC` and `Volume_FCC`) and the code runs fine because it realizes there's nothing in those directories for training.

**Comment by rohskopf** [comment]
Actually the FitSNAP JSON scraper didn't like that, I had to put a hidden file to keep those directories on GitHub. I'll think of something else.

**Comment by ldwillia** [comment]
Oh huh, didn't think about github not wanting to have empty folders around. I can probably add a for loop to check for the lack of any subdirectory in the JSON directory between making the config obj and calling the scraper and just prune them from the config object.

**Comment by rohskopf** [comment]
@ldwillia ldwillia Curious about the output in the active learning loops:
```
                               ncount            mae           rmse       rsq
Weighting  Testing  Subsystem                                                
Unweighted Training Energy         21       0.303358       0.616780  0.996291
                    Force        1416       0.149962       0.254490  0.976465
                    Stress        126  346535.825287  992758.241286  0.930529
           Testing  Energy         12       0.743251       1.219533  0.992444
                    Force         960       0.163074       0.278270  0.970343
                    Stress         72  320328.459434  816580.991227  0.976797
weighted   Training Energy         21       0.450159       0.715084  1.000000
                    Force        1416       0.149961       0.254490  0.976465
                    Stress        126       0.018682       0.078882  0.999990
           Testing  Energy         12       0.743251       1.219533  0.992444
                    Force         960       0.163074       0.278270  0.970343
                    Stress         72  320328.459434  816580.991227  0.976797
```
Are these errors supposed to decrease each loop, or how should we interpret them?

**Comment by ldwillia** [comment]
So that is printing the error_analysis() report for the overall dataset ("*ALL") at each loop. Ideally the testing errors should be going down each loop, but there's no guarantee that this will always happen. It depends on the makeup of your test set and how well that matches what the active learning is identifying as high uncertainty structures. 
Particularly when using the group weights from a DAKOTA optimization, it's possible to have very little change at all if you added a structure with very low group weights.
Also, at least at the start, the training errors usually go up as you add very disparate structures into the training data.

**Review by rohskopf — APPROVED** [review]
Working active learning script using the FitSNAP library. This involves inputs and settings that should be read about before using. More details can be in a future PR. Thanks @ldwillia !

**Pull request merged**
