### PR TITLE
David output

### PR DESCRIPTION
**Pull request by athomps**
See email

### CODE REVIEW

**Comment by mitwood** [comment]
I do not like that this is not implemented as an option to users, everyone will be outputting mass amounts of data unknowingly. This will only work in serial as well, output from a calculator not handled by parallel tools will not be handled correctly. Why would the A matrix change from calculator to error calculation anyway? Also, there are hard coded values that will break when changing the number of descriptors in the new file initialize_array (not sure what this is for anyway). Use pt.create_shared_array() for this. Lets leave this on a separate branch or fork until there is more polish on this addition.

**Comment by athomps** [comment]
@mitwood This was my mistake. I was intending to push it to https://github.com/dmozapiain2001/FitSNAP/tree/David_output​

**Comment by charlessievers** [comment]
I have this (as an option) in my test version that I use, I'll add it with my next PR. I did not realize other people would want it as well.

**Comment by mitwood** [comment]
No problem, just was giving some rapid feedback on PRs. @charlessievers note that this addition is using compute sna/atom rather than compute snap in order to get per-atom descriptors for energy, rather than the sum which is used for total energy regression. Did your version do this as well?

**Comment by charlessievers** [comment]
No, I was just printing out the summed descriptors. I could try and think of a clean way to do unsummed descriptors, it is quite a lot of information (some useful).

**Comment by mitwood** [comment]
You're right @charlessievers its a lot of data, but other solvers and model forms will require this detailed information. SNAP as a linear model can do this pre-summation and it doesnt matter during regression, not true for arbitrary nonlinear models. Lets think about how we can expose this data for all potential descriptor types that LAMMPS can handle.

**Comment by athomps** [comment]
I can see the benefit of getting LAMMPS to output a lot of intermediate data on descriptors.

**Comment by mitwood** [comment]
Agreed, but ideally as their own data objects rather than outputting to files. I would like to see this code evolve toward a streamlined model construction tool, maybe we should include an option to terminate after calculating descriptors in case users want to substitute with their own methods for model generation and training.

**Pull request closed without merging**
