### PR TITLE
Extending FitSNAP for the integration in Par-splice

### PR DESCRIPTION
**Pull request by jan-janssen**
**New Functionality:** 
* Run FitSNAP directly from a Jupyter Notebook. 
* Provide MPI Communicator as external Input. 

Demonstrations of both examples are available https://github.com/jan-janssen/fitsnap-demo 

**Changes:** 
To enable these changes the command line option had to change. Rather than using `python -m fitsnap3` it is now available as `python -m fitsnaprun`.  

**Explanation:** 
The changes are primary based on the implementation of a singleton class: 
```
class Singleton(type):
    _instances = {}

    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
        return cls._instances[cls]
```
used for both the `config` and the `pt` e.g. parallel tools.

### CODE REVIEW

**Comment by athomps** [comment]
@jan-janssen Thanks for this contribution.  It will require require further development before we can merge it.  Have you tested it for backwards compatibility on all the examples in ./examples?

**Comment by jan-janssen** [comment]
I tested all the examples just now and they work like before, the only
difference is, it is now:

    python -m fitsnaprun inputfile

While before it was:

    python -m fitsnap3 inputfile

This is the consequence of enabling the direct importing. An alternative
option would be to move all files to something like pyfitsnap3 then the
previous function call would remain the same but it would result in many
more file modifications based on moving the files around which could
complicate merging other pull requests later on.

Best,

Jan

**Comment by charlessievers** [comment]
This PR raises a few interesting questions. 
Do we need FitSNAP as a module? (Downsides, upsides?)
Should we use metaclasses or class decorators for a singleton? I am preferential to class decorators.

On another thought.
What was the thought process behind moving parallel output options to a new python file? If we are going to do this, let's make a parallel folder to contain all the files that create objects which use access to MPI communicators.

**Comment by jan-janssen** [comment]
- The reason for the module is to integrate it with other python frameworks, sharing the same MPI communicators, as demonstrated [here](https://github.com/jan-janssen/fitsnap-demo/blob/master/demo-parallel.ipynb). 
- With the decorator it becomes a function rather than a class, that is I why chose the meta class. 
- Finally the motivation to move parallel output to a separate module is primarily that it requires an instance of parallel tools.

**Comment by charlessievers** [comment]
> * The reason for the module is to integrate it with other python frameworks, sharing the same MPI communicators, as demonstrated [here](https://github.com/jan-janssen/fitsnap-demo/blob/master/demo-parallel.ipynb).

@jan-janssen those are some good reasons to replace or add them onto the current FitSNAP module package setup, which I agree would be nice features to add. 
My major concern is that there is a lot of parallelism behind the scenes and opening up the communicators to everyone is something I have actively tried to avoid at almost every step in writing FitSNAP, this will also increase difficulty in maintaining FitSNAP. I believe passing a communicator and being able to deconstruct FitSNAP in this way should be features for experienced python+MPI users only. 
We just need to be careful here since you are suggesting some rather large fundamental changes that may be possible as additions instead. @athomps @mitwood what are your guys opinions?

> * With the decorator it becomes a function rather than a class, that is I why chose the meta class.

:thumbsup: 

> * Finally the motivation to move parallel output to a separate module is primarily that it requires an instance of parallel tools.

Great, then let's make a separate folder for parallel activity.

**Comment by jan-janssen** [comment]
An alternative approach would be to move everything that is currently in `fitsnap3` to something like `pyfitsnap3` and move `runfitsnap` to `fitsnap3`. With this the user experience for the current users would remain exactly the same and the advanced users could decide to use `pyfitsnap3` directly.

**Comment by perez-danny** [comment]
Guys, there might be a problem with this. I tried running a fit  twice following Jan's serial example notebook, i.e., by executing 
```
#result is the same whether the next two lines are commented or not.
#pt = ParallelTools()
#config = Config(arguments_lst = ["Ta-example.in"])
snap = FitSnap()
snap.scrape_configs()
snap.process_configs()
snap.perform_fit()
snap.write_output()
```
again after the first fit. I get a `NameError: name is already in dictionary`. pt and config seem to preserve their state from one execution to the next. Any way to wipe them clean between each fit? We would need this feature to work to refit when we get more DFT data.

**Comment by charlessievers** [comment]
An alternative solution is we create a file, let's call it `run_fitsnap.py` for now.
```
from runpy import run_module
from mpi4py import MPI
import sys

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

color = rank % 2
local_comm = comm.Split(color)
MPI.ADDED_COMM = local_comm

original_arguments = sys.argv
new_arguments = ['fitsnap3', 'Ta-example.in', '--overwrite']
sys.argv = new_arguments

if color == 0:
    run_module(sys.argv[0], run_name='__main__', alter_sys=True)

sys.argv = original_arguments

```
We change line `135` of `parallel_tools.py` to
```
try:                             
    self._comm = MPI.ADDED_COMM  
except NameError:                
    self._comm = MPI.COMM_WORLD  
```
Then run `mpirun -n 4 python /path/to/run_fitsnap.py` while in the Ta Linear Example folder.

Note: Make sure fitsnap3 is in your PYTHONPATH

**Pull request closed without merging**
