### PR TITLE
New pace calculator

### PR DESCRIPTION
**Pull request by charlessievers**
Pace calculator beta version.

Changes made to accommodate an additional calculator. (Added separate outputs, separate sections, separate calculators)

### CODE REVIEW

**Review by athomps — APPROVED** [review]
I approve!

**Review by mitwood — DISMISSED** [review]
Code changes look good. ACE Readme, or elsewhere, needs to identify the change to the lammps build process that are needed to make this work.

**Comment by charlessievers** [comment]
This still needs more testing and work before it is merged. I think I might want to parallelize the .ace file calculation and add in a check to see if the .ace file contains the required information.

**Review by mitwood — CHANGES_REQUESTED** [review]
Training data should be removed from this example since it can be referenced to the other Ta example, avoid bloat. Import check needed for ard and lasso solvers.

**Comment by mitwood** [comment]
1) coupling_coefficients.ace needs to be removed at the start of each run to avoid spurious errors, or users can define a specific filename to read from to save a little time.
2) For now all new solver types have their method specific commands added into the general SOLVER section of the input file.
3) Example PACE fits run, but do not reproduce the 'standardized' coefficients in the respective sub-directories. This needs to be addressed in future PRs, specifically the version tags of LAMMPS needs to be added.

Each of these items can be addressed in a future PR as the functionality of having ACE fits working outweighs fixing these minor bugs.

**Review by athomps — APPROVED** [review]

**Pull request merged**
