### PR TITLE
adding stress optimization and initial weight usage to genetic algo (WIP)

### PR DESCRIPTION
**Pull request by ldwillia**
Here's the bulk of the changes for stress optimizing and also initial weights usage in the genetic algorithm code. There's a few functions I haven't updated yet (print final, simulated anneal, the internal part of the latin hypercube, though I think that doesn't need changes).

As implemented currently, this would always try to optimize stress even if user doesn't want that. We should make that part of the calculation optional before merging into main. Heading home for the weekend now, but figured I would put this up in case you guys want to work on it before I get to finishing it.

### CODE REVIEW

**Comment by megmcca** [comment]
hey @ldwillia, this is very helpful thanks! and thanks for the detailed notes.
as you mentioned, the initial version always assumes stress fitting is requested.  i've updated it to account for most use cases that i can foresee.
there were also bugs/crashes with inputs that didn't have the [GROUPS] 'vweight' column set up, so i've implemented the following behavior:
- if stress fitting = 0 and vweights present: fits/prints as expected
- if stress fitting = 1 and vweights not present: elegant crash with instructions
- if stress fitting = 0 and vweights present: fits/prints 0.0 for all vweights
- if stress fitting = 0 and vweights not present: fits as expected (no vweights column printed for easy copy-paste)

i did not touch simulated_anneal... maybe we should archive it somewhere

**Comment by ldwillia** [comment]
@megmcca Thanks! Regarding the simulated anneal: I haven't really looked at it but I assume it doesn't need extensive changes. I don't know how useful it is, though. @jmgoff , do you think that the simulated anneal is worth maintaining or should be archived?

**Comment by ldwillia** [comment]
Stuck a check with error message if trying to use simulated anneal with stress fitting enabled. (Have not tested simulated anneal functionality though). Moving this out of draft mode.

**Review by megmcca — APPROVED** [review]
With @ldwillia's updates, genetic_algorithm now fully compatible with general FitSNAP input. Thanks!

**Pull request merged**
